### ISSUE TITLE
Highlighting Approach is Information Lossy

### ISSUE THREAD

**Issue by Austio** [doximity/es-elasticity#62]
The current highlighting approach causes information loss on nested fields that are matched. 

For instance, if we had a result that included both `location.address` and `location.city` it would cause the highlighter to merge these together into a single highlighted field.

https://github.com/doximity/es-elasticity/blob/00c5beabdd6033de78060e748aac4fe2985a6922/lib/elasticity/index_mapper.rb#L148-L156

I think it would be better to either
 - Expose the Raw json results to the end user
 - Provide a way to declare the strategy to handle this at query time so that if a user just wants this interpretted version, they get it by default, but could provide something like `raw` to the search as an argument.  This would enable more advanced use cases and act as an escape hatch in cases like this.

**Comment by brupm** [comment]
@divoxx We can't lose that data, we need it to properly highlight the content on the view.

**Comment by brupm** [comment]
@divoxx let us know how you want to proceed. Ideally, we are not throwing away data as it is needed.

**Comment by divoxx** [comment]
@brupm I talked to @Austio offline. It looks like what we have right now is good enough for the use case. Highlight support overall can and should be improved but it also sounds like adding a better support would be more work than we are willing to devote and that we could benefit from learning a bit more about how the data can be used.

I'm personally against adding the raw access to the data because it breaks the abstraction of the library and makes it leaky. I do agree that all the information needs to be available (and the majority currently is) but we should focus on designing a good abstraction rather than giving direct access and forcing applications to conditionally handle highlight data and having to manually match against the data provided by the abstraction/model. For example, we should be able to match subfields properly to the document properties rather than give the application a "foo.bar" key, etc.

**Comment by brupm** [comment]
I would like to be able to pass in a flag whenever needed and retrieve raw results, the party doing so is responsible for handling it. 

This is helpful while testing and makes it so we can let the consumer decide how to deal with the data as opposed to having to make a change to es-elasticity every time ES changes the response or ads a new API. 

Right now, elasticity dumps data from the returned JSON when it isn't explicitly told what to do with it, this is less than optimal behavior. 

Having said that, I'm OK deferring this to a separate story to add full abstraction support the highlight block. @Austio will create a separate story.

cc @Austio  @davidbl if you have anything to add.

**Comment by divoxx** [comment]
@brupm it doesn't drop the data, it makes the highlighted data available through the highlighted object and with @Austio PR it allows to easily get the highlighted attr names too. The only part that is missing is the proper handling of subfields.

We agree that the library should provide all the data, but I think it should be done in a way that is consistent with the library and not through a leaky abstraction. Bad abstractions are really hard to change after they've been released and I'd rather take the time to do something correctly, specially if the current implementation already provide the necessary bits for the use case at hand.

I think there is some value in allowing the raw data to be accessed for debugging purpose or very specific corner cases, but it shouldn't be the "main" way of interacting with the library and the less applications depend on the specific wire format, the better.

**Comment by brupm** [comment]
For the record, it does drop data, it drops the subfields. Story to handle
it in the future: https://www.pivotaltracker.com/story/show/158921721
